# Run the test suite
name: Run test suite

# Runs on pushes on all branches
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Node dependencies
        run: npm clean-install
      - name: Run test suite
        run: npm test -- --coverage